[project]
name = "self-eval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "datasets>=3.3.0",
    "graphviz>=0.20.3",
    "litellm>=1.61.3",
    "matplotlib>=3.10.0",
    "tenacity>=9.0.0",
    "tqdm>=4.67.1",
]
